name: web-client

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: install
      working-directory: sub-systems/web-client
      run: npm install
    - name: audit
      working-directory: sub-systems/web-client
      run: npm audit
    - name: lint
      working-directory: sub-systems/web-client
      run: npm run lint
    - name: test
      working-directory: sub-systems/web-client
      run: npm run test
